### ISSUE TITLE
Fix CSS styling

### ISSUE THREAD

**Issue by chrissotraidis** [subspace/astral#303]
Noting the following CSS styling issues when resizing windows in the browser:

- Links/social links at the bottom of explorer.subspace.network look misaligned. 

![Image](https://github.com/subspace/astral/assets/56282582/18bd36aa-58cc-4a5c-90ce-705d74f4454e)

- Remove Reddit social link, as our community is now banned and we have not decided on if we will re-add it.

- When resizing the window on the explorer, smaller windows make it so you can no longer see the Account, Blocks, Extrinsics, Events, and Logs pages. Below is an attached example of this happening. Users with differing sized windows might not notice that these pages are there.

![Image](https://github.com/subspace/astral/assets/56282582/23c900a3-749a-402c-bf16-6daf70e0eec8)

**Comment by natachadelarosa** [comment]
On Mobile devices the menu hides into a burger menu

**Comment by BrianBelhumeur** [comment]
Fixed with PR #304
