### ISSUE TITLE
Incorrect Qualified Reward Address on EVM Page

### ISSUE THREAD

**Issue by ImmaZoni** [subspace/astral#380]
Taking a look at the qualified reward address section on the EVM side of the explorer, it claims there are `227,006` addresses which have qualified. Seems to be incorrect in some manner

![image](https://github.com/subspace/astral/assets/31865152/0b606adb-f2ec-4757-b740-e1199a073c54)

**Comment by jfrank-summit** [comment]
I think this is a labeling error but the number looks right. This should be something like "Wallet addresses".
