### ISSUE TITLE
Feature Request: Implement Search Box for Dynamic Information Retrieval on Farmers Leaderboard and Operators Leaderboard and Nominators Leaderboard

### ISSUE THREAD

**Issue by tradebigshort** [subspace/astral#406]
Desired Feature
Integration of a search box within the Farmers Leaderboard for quick and direct information retrieval.

Problem Statement
The current Farmers Leaderboard interface lacks a quick search feature, obliging users to manually navigate through pages or download page data to locate specific information. This process can be inefficient and time-consuming, particularly for users dealing with extensive datasets.

Proposed Solution
I suggest incorporating a search box at the top of the leaderboard that would enable users to input search queries and instantly filter the displayed results in the table. This functionality should be designed to work without the need to reload the entire page or navigate away from the current view.

Specific Features Expected:
An easily accessible search field at the top of the leaderboard.
The ability to filter and refresh the table contents in real-time based on user input.
Compatibility with various data fields present in the table (such as Account ID, Block Rewards, Vote Rewards, etc.).
A responsive and user-friendly interface that integrates seamlessly with the existing user experience.
Expected Impact
This enhancement would significantly improve user experience by streamlining the access to and search for specific data, which is invaluable for users managing large data volumes or seeking detailed information on particular accounts.

I believe this feature would greatly enhance the efficiency and usability of the leaderboard interface. I look forward to seeing this suggestion considered in a future update.

Thank you for your attention to this matter and for your ongoing efforts to improve Subspace !

![image](https://github.com/subspace/astral/assets/46727466/ef7d8ca4-9591-484d-ab90-e88642ed794b)

Best Regards,

tradershort

**Comment by natachadelarosa** [comment]
Hi @tradebigshort  we recently implemented a search bar for leaderboards, which is currently available on the site, it allows you to search with the id field of the table (accountAddress or Id). I will add a ticket to follow the work on the other requested search parameters.

**Comment by tradebigshort** [comment]
Thank you natachadelarosa !
