### ISSUE TITLE
Feature Request: Excel Export Option for Entire Dataset of Each Leaderboard Tab 

### ISSUE THREAD

**Issue by tradebigshort** [subspace/astral#407]
Desired Feature
Addition of an Excel export option for the complete dataset of each distinct leaderboard tab: Farmers, Operators, and Nominators.

Problem Statement
While the current leaderboard interface provides a 'Download page data' feature, it is limited to single-page data and does not differentiate between the various tabs like Farmers, Operators, and Nominators Leaderboard. Users interested in extensive data analysis require a more efficient way to export the full dataset from each specific category.

Proposed Solution
Introduce an export feature that allows users to download the entire dataset from each leaderboard tab in an Excel format. This feature should be accessible from each tab separately, enabling a tailored download experience.

Specific Features Expected:
An 'Export All to Excel' button on each leaderboard tab: Farmers, Operators, and Nominators.
The functionality to export all entries across all pages within a selected tab to a single Excel (.xlsx) file.
Proper formatting within the Excel file, including column headers and appropriate data structuring for immediate analytical use.
Expected Impact
This feature would streamline the data extraction process, making it much easier for users to perform comprehensive analyses without the need to manually compile data across multiple downloads. It would significantly enhance the platform's utility for data-driven decision-making.

I hope this feature will be considered for future development to enhance user efficiency and satisfaction with Subspace .

Thank you for your commitment to continuous improvement.

best regards,

traderbigshort
![image](https://github.com/subspace/astral/assets/46727466/cb6eee48-37ee-4339-9e10-20d3608e8f5e)

![image](https://github.com/subspace/astral/assets/46727466/61990c6d-4b65-48ad-98c0-db20464a171a)

**Comment by natachadelarosa** [comment]
This task was completed with the contribution from @clostao. 

Thank you @tradebigshort for the comprehensive feature description that led to this awesome contribution, continue contributing to our project!

Thanks again!
