### ISSUE TITLE
PARAMS ERROR

### ISSUE THREAD

**Issue by ivankaslovakia** [subspace/astral#411]
hello, some bug on it
thanks for debug

Ivanka
![2024-01-05 16_34_59-Subscan _ Subspace Gemini 3G Account Detail_ st73svQMUQenpjPrN5sRaRqRo8sbdSm8Bak](https://github.com/subspace/astral/assets/85197207/72240f5e-26de-4606-ac39-b4f2406a9a1d)

**Comment by nazar-pc** [comment]
Can you describe how you got this error, which page is it on, etc?

**Comment by ivankaslovakia** [comment]
https://subspace.subscan.io/account/st73svQMUQenpjPrN5sRaRqRo8sbdSm8BakJhpHJJd1cAKKdC

**Comment by jfrank-summit** [comment]
This has been fixed by Subscan.
