### ISSUE TITLE
STILL PROBLEMS WITH SYNCING→ FIX IT PLS

### ISSUE THREAD

**Issue by ivankaslovakia** [subspace/astral#412]
![2024-01-05 19_22_27-Windows PowerShell](https://github.com/subspace/astral/assets/85197207/dde8405c-c8e5-4ca5-9ef0-1236ea273659)

**Comment by jfrank-summit** [comment]
This is the Astral block explorer repo, this is a node error. Please report in appropriate [repo](https://github.com/subspace/subspace/issues) and add much more detail, as a screenshot is not nearly enough info for our team to investigate.

**Comment by ivankaslovakia** [comment]
seri3m na c3lu subinku,doj3bat3 to j3 na sračk4
