### ISSUE TITLE
subscan explorer not working

### ISSUE THREAD

**Issue by vamsick29** [subspace/astral#413]
![image](https://github.com/subspace/astral/assets/79183358/bf0a36c0-0a70-4ef9-a805-1a07bf7d2b7a)
![Screenshot (1310)](https://github.com/subspace/astral/assets/79183358/5ff1f2e7-c599-4019-84fd-b27316f1c19a)

**Comment by jfrank-summit** [comment]
This was reported to Subscan and should have been fixed. I'm closing this as it is not an Astral issue.

**Comment by vamsick29** [comment]
Thanks issue is solved
