### ISSUE TITLE
A Staking frontend issue (not affecting functionality)

### ISSUE THREAD

**Issue by DianaPertseva** [subspace/astral#444]
Spinning indefinitely after staking: 

![Image](https://github.com/subspace/astral/assets/74624874/351d2429-f3f1-4f86-89dd-9e1ce1619734)

I don't think we need to fix it now, since we're moving Staking into Astral, just to note!

**Comment by marc-aurele-besner** [comment]
From the look of it, this seems https://github.com/subspace/staking-interface and not Astral

**Comment by marc-aurele-besner** [comment]
This bugs is unrelated to Astral, it was in staking interface repo, and that repo has been archived
