### ISSUE TITLE
Inscriptions on subspace

### ISSUE THREAD

**Issue by vamsick29** [subspace/astral#450]
Recently Inscriptions are getting hyped in various blockchain and its promising.so inscriptions on subspace will also will be a greater thing if we implement it along with mainnet launch
code:
data:,{"p":"sub-20","op":"mint","tick"SUBS","amt":"1000"} 
Total supply can be 21 million
And indexing can be done within specific block and and when it reach max mint amount indexing can be stopped at that block.

**Comment by jim-counter** [comment]
Interesting idea. This might be better off as a discussion on our forum. Please raise a thread here: https://forum.subspace.network/c/feedback/2. It's not something we'd implement in this repo for Astral our block explorer.

**Comment by vamsick29** [comment]
ok sir thankyou i  raise a thread on forum
