### ISSUE TITLE
Pagination Failure on Mining Rewards Page - Results Reset to First Page

### ISSUE THREAD

**Issue by ImmaZoni** [subspace/astral#470]
## Description
On the Gemini 3g Mining Rewards page (`https://explorer.subspace.network/#/gemini-3g/consensus/accounts/WALLETADDRESS/rewards`), there is a bug in the pagination functionality. When clicking the ">" button to navigate to the next page of results, the next page appears only briefly before reverting back to the first page.

## Steps to Reproduce
1. Go to `https://explorer.subspace.network/#/gemini-3g/consensus/accounts/WALLETADDRESS/rewards`
2. Click on the ">" button to navigate to the next page of mining rewards.
3. Observe that the next page of results is displayed momentarily before returning to the first page.

## Expected Behavior
Clicking the ">" button should successfully navigate to and display the next page of results.

## Actual Behavior
The next page of results flashes briefly, then reverts to displaying the first page of results.

## Notes
- This issue persists even when changing the display setting to "Show 50".
- This issue may be related to lack of enough rewards to generate a second page. 
- Or This issue might be related to asynchronous data fetching or state management in pagination.

_Note: This issue was sourced from the community: https://discord.com/channels/864285291518361610/1197112595329589288_

**Comment by natachadelarosa** [comment]
Hi @ImmaZoni , I couldn't reproduce this behavior, can you validate again if it stills happens to you?
