### ISSUE TITLE
GDPR startement for data collection

### ISSUE THREAD

**Issue by DianaPertseva** [subspace/astral#500]
I think we can use the same text we have on our website: 
"By clicking “Accept All Cookies”, you agree to the storing of cookies on your device to enhance site navigation, analyze site usage, and assist in our marketing efforts. View our [Privacy Policy](https://subspace.network/gdpr-privacy-statement) for more information."

**Comment by natachadelarosa** [comment]
@DianaPertseva this was added yesterday with this PR: https://github.com/subspace/astral/pull/497
