### ISSUE TITLE
Operators View - Status can be very long

### ISSUE THREAD

**Issue by 0xjeremyfrank** [subspace/astral#547]
The status field on the[ operators page](https://explorer.subspace.network/#/gemini-3h/operators) can be very long and push `Actions` offscreen.

![image](https://github.com/subspace/astral/assets/37932802/75e0c9f4-6bfb-4d65-8ac9-28e61a1abae2)

**Comment by marc-aurele-besner** [comment]
This has been fix in #543 :)
