### ISSUE TITLE
The `Download full board` button in the leaderboard does not work

### ISSUE THREAD

**Issue by marc-aurele-besner** [subspace/astral#622]
## The `Download full board` button in the leaderboard does not work

![Screenshot 2024-06-17 at 1 47 24 PM](https://github.com/subspace/astral/assets/82244926/97ffe933-c344-4259-9cdc-27bf2fe120b0)

**Comment by SandipGyawali** [comment]
@marc-aurele-besner if it's open to contribute can i look at it ??

**Comment by marc-aurele-besner** [comment]
> @marc-aurele-besner if it's open to contribute can i look at it ??

Sorry, I did not see your message, I just made a [PR](https://github.com/subspace/astral/pull/624) for this issue feel free to suggest change or look at #623 since I see further issue when trying to download full data on page like Operators
