### ISSUE TITLE
Registering with a keystore that use a URI (and not a mnemonic) seems to result in a wrong signing key

### ISSUE THREAD

**Issue by marc-aurele-besner** [subspace/astral#705]
## Registering with a keystore that use a URI (and not a mnemonic) seems to result in a wrong signing key

The signing key of a URI seems to be wrong compared to a mnemonic, or the change to use auto-sdk cause this issue?

**Comment by jfrank-summit** [comment]
The specific issue I was facing was that the URI had "_"s in it and this [line](https://github.com/subspace/astral/blob/d22e18dfaa03b4bececdcaac50bfdea95e6d4b12/explorer/src/components/Operator/OperatorStake.tsx#L253) removes them.

**Comment by marc-aurele-besner** [comment]
> The specific issue I was facing was that the URI had "_"s in it and this [line](https://github.com/subspace/astral/blob/d22e18dfaa03b4bececdcaac50bfdea95e6d4b12/explorer/src/components/Operator/OperatorStake.tsx#L253) removes them.

Ah make sense, I could change the regex, the only thing I really need to filter out is the " "
