### ISSUE TITLE
Support Gemini 3d system and payment domains

### ISSUE THREAD

**Issue by achiurizo** [subspace/astral#71]
System domain public RPC: 
- `eu-0.system.gemini-3d.subspace.network`
- `eu-1.system.gemini-3d.subspace.network`

Payments domain public RPC: 

- `eu-0.payments.gemini-3d.subspace.network`
- `eu-1.payments.gemini-3d.subspace.network`

- [ ] setup Archive for System domain
- [ ] setup Archive for Payments domain
- [ ] setup Squid for System domain
- [ ] setup Squid for Payments
- [ ] enable Domain tabs on the UI (tabs: `core`, `system`, `payments`)

**Comment by natachadelarosa** [comment]
Left open to review when adding the new domains @chrissotraidis
